version: '2'

networks:
  internal:
    driver: bridge

services:

  cassandra:
    build:
      context: .
      dockerfile: cassandra.dockerfile
    container_name: msl-cassandra
    networks:
     internal:
       aliases:
        - msl-cassandra
    environment:
      CASSANDRA_START_RPC: "true"
  
  client:
    build:
      context: .
      dockerfile: client.dockerfile
    container_name: msl-client
    networks:
     default:
       aliases:
        - client-external
     internal:
       aliases:
        - msl-client
    ports:
     - 3000:3000

  server:
    build:
      context: .
      dockerfile: server.dockerfile
    container_name: msl-server
    command: ["socat", "TCP-LISTEN:9042,fork,reuseaddr", "TCP:msl-cassandra:9042"]
    networks:
     internal:
       aliases:
        - msl-server
     internal:
       aliases:
        - server-external
    ports:
     - 9003:9003
     - 9002:9002
     - 9001:9001
  
  socat:
    image: mondev/dind:dind
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    command: ["docker", "exec", "msl-server", "npm", "run", "serve-all"]